version: '3.8'

services:
  gdpr_backend:
    build: ./backend
    container_name: gdpr_backend
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  gdpr_frontend:
    image: nginx:alpine
    container_name: gdpr_frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gdpr-frontend.rule=Host(`gdpr.deft.work`)"
      - "traefik.http.services.gdpr-frontend.loadbalancer.server.port=80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gdpr_backend

  gdpr_admin_frontend:
    image: nginx:alpine
    container_name: gdpr_admin_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-gdpr-frontend.rule=Host(`admin-gdpr.deft.work`)"
      - "traefik.http.services.admin-gdpr-frontend.loadbalancer.server.port=80"
    volumes:
      - ./admin-frontend:/usr/share/nginx/html:ro
      - ./nginx-admin.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gdpr_backend
